### PR TITLE
Updated project files

### PR DESCRIPTION
**Pull request by skeetor**
Added nasm files to project structure.
Fixed SDK versions and build failures in different build configurations
Move build instructions to main directory to display it in github

### CODE REVIEW

**Comment by tonioni** [comment]
Why did you change compiler version? (PlatformToolset).  Only ReleaseXP build use old version.

**Comment by skeetor** [comment]
In your build instructions it mentions VS2017 and I don't have VS2019 installed, I installed the SDK to match yours, but I don't want to switch compiler as well.

**Comment by skeetor** [comment]
Shall I revert it to 142?

**Comment by tonioni** [comment]
Yes because I always use latest version :)

**Comment by skeetor** [comment]
I reverted the platformtoolset to your version and squashed it. Only PlatformToolset I changed is the one for WindowsXP because v142 doesn't support XP any longer.

**Pull request merged**
