### PR TITLE
Fix for missing bottom lines in host window

### PR DESCRIPTION
**Pull request by skeetor**
This PR changes:

1) The documentation is updated as the manual compilation of assembler sources is no longer needed but was mentioned in the README.
2) A hard coded offset caused a few lines in the final rendering to not displays the last few lines in the display.
3) Set fixed width font on the debugger GUI

### CODE REVIEW

**Comment by skeetor** [comment]
Here you can see the difference 
SCR

Tested it with different DPI (up to 200%) settings and full screen mode on W10.

**Comment by tonioni** [comment]
I don't think that is correct fix for the black part. It is supposed to limit internal buffer to TV-like size and not directly related to how display finally appears. Include your config file and winuaelog.txt.

**Comment by skeetor** [comment]
Actually this was not supposed to remove the black bars, it was just to avoid that the last lines of the Amiga display get painted into the black bar thus being not visible, as can be seen on the screenshot I provided. As far as I understand, the code in win32_scaler.cpp is supposed to "squeeze" the Amiga display inside the host display area (depending on the settings). Which log do you want? the one with, or without the fix. As for showing this issue, you can take any 

[config_report.zip](https://github.com/tonioni/WinUAE/files/4008125/config_report.zip)

**Comment by skeetor** [comment]
Any news on that. I don't see why you think this is wrong.

**Comment by tonioni** [comment]
Does top of screen also have identical sized black bar? If it does, it is basically working as designed. "Default" filter mode is a bit special..

**Comment by skeetor** [comment]
The bars are still caclulcated normally as before. I just reduced the virtual screensize, because the bottom lines were overpainted by the bars. So my change "squeezes" the lines into the visible area, so that the full screen is visible. It's a already a hardocded "magic number" anyway, so adjusting it a bit, to make it visually better doesn't change any logic.

**Comment by tonioni** [comment]
I'll need to check later where the black part really comes from...

**Pull request merged**
