### PR TITLE
added missing #ifdef statements

### PR DESCRIPTION
**Pull request by midwan**
Mostly those requiring DEBUGGER, but also a few more

### CODE REVIEW

**Comment by tonioni** [comment]
Looks good but I don't like ifdefs that duplicate almost identical code lines (mainly floppybridge changes) because almost certainly I will miss the other one they will be out of sync sooner than later. I am not sure whats the best option but at least this isn't good way.

**Comment by tonioni** [comment]
Looks ok but why did aros rom change?

**Comment by midwan** [comment]
@tonioni 
It didn't - you had it ignored from `gitignore`, so I removed that from there and therefore the file is now showing as part of the repository. I think there's no reason to exclude it, as it's needed for building anyway :)

**Comment by tonioni** [comment]
Ah, right :)

But it is really long, ugly and pointless file (for any other purpose than compilation). Thats why I'd like to keep it out.
(filesys_bootrom is technically same but it is at least short and sources are also included)

**Comment by midwan** [comment]
@tonioni 
Yeah, I know - but if you need it to compile the thing, better have it in the repository regardless.

In Amiberry, I've completely removed it and I'm using external Aros ROM files, instead. That way, I can upgrade them if newer versions come along easily.
Not sure if you also prefer that approach, as it means that new releases will need to have those binaries packaged with them, instead of having it embedded in the executable.

**Pull request merged**
