### PR TITLE
JIT: Don't call uae_vm_free in LazyBlockAllocator destructor

### PR DESCRIPTION
**Pull request by FrodeSolheim**

### CODE REVIEW

**Comment by rofl0r** [comment]
can we keep the code C compatible ? your C++ class prevents porting it to PUAE

**Comment by FrodeSolheim** [comment]
I don't mind that in principle. It isn't "my class" btw, this class was merged from the ARAnyM JIT compiler, and I'm not going to rewrite it without a good reason (though converting to plain C is trivial).

Once there is active development and *actual releases* for a C-based PUAE, I'll be happy to accept C compatibility patches...

**Comment by rofl0r** [comment]
i see. guess i need to ping @GnoStiC another time to see if he's willing to continue working on PUAE... if not i could probably help out. having a proper PUAE tarball release is on my wishlist since years...

**Comment by rofl0r** [comment]
woot... it seems @GnoStic has deleted his account/PUAE repo ?!

**Pull request merged**
