### PR TITLE
Vs2022 fixes

### PR DESCRIPTION
**Pull request by midwan**
This PR tries to improve the Visual Studio solution/projects as follows:
- Disable `vcpkg` from the project options. Since you're using a hardcoded path with pre-compiled libraries, having this enabled would conflict with the libraries available from there, if you had any installed (e.g. libFLAC would fail on a x64 build). Disabling it ensures that only the libs you specified will get picked.
- Updated the solution/projects to Visual Studio 2022 (latest stable release)
- Removed unneeded projects (singlefilehelper, resourcedll, fdrawcmd, decompress, consolewrapper). Not sure if you want these around, if so let me know and I'll bring them back.
- Configure project dependencies, so that all required projects build automatically when building the "winuae" project. Hopefully I got this right, but feel free to let me know if it needs further adjustments.

### CODE REVIEW

**Comment by midwan** [comment]
@tonioni forgot to mention, this includes my fix for the inverted x/y gfx coordinates, since I had that in `master`. I can revert that commit however, if you want.

**Comment by tonioni** [comment]
> Configure project dependencies, so that all required projects build automatically when building the "winuae" project.

This is disabled by design because it would cause unneeded recompilations when some header file changes (for example options.h).  "gen" projects are generally only needed to be compiled once. After that only winuae needs to be compiled when some file changes.

**Comment by midwan** [comment]
> > Configure project dependencies, so that all required projects build automatically when building the "winuae" project.
> 
> This is disabled by design because it would cause unneeded recompilations when some header file changes (for example options.h). "gen" projects are generally only needed to be compiled once. After that only winuae needs to be compiled when some file changes.

But it would take only a few seconds more if that were to happen, whereas if a change was made which _did_ need the "gen" projects to re-run (such as the recent IPL updates), you'd run into problems. So from one side you have a few extra seconds of compile time in the worst-case scenario, on the other side you have potential problems while compiling or running the main executable. In my mind, it's always better to go for option 1 in these cases.

Not to mention it removes a few manual steps from the process as well, in case you wanted to automate builds with a pipeline for example.

In the end, it's your project of course - I can remove those if you don't want them.

**Comment by tonioni** [comment]
It is not just a few seconds. For example those huge cpuemu_x files don't compile instantly. If I see those getting created automatically and pointlessly, I will get annoyed really quickly.

I won't accept any changes that makes it worse for me or that makes it simpler for everyone else but me.

resourcedll should not be removed, others you mentioned are not needed. It is important when building final release version.

**Comment by midwan** [comment]
@tonioni 
OK, I've reverted the changes to the Solution file, per your request.

**Pull request merged**
